[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf"
    refreshPeriod = "168h"
["antigen.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "archive"
    url = "https://github.com/NvChad/NvChad/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
