"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Thomas"
email = "substantialimpulse@pm.me"

[ui]
default-command = "log"
merge-editor = "meld"
# diff-editor = "meld"
