"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Thomas"
email = "substantialimpulse@pm.me"

[ui]
default-command = "log"
merge-editor = "meld"
diff-editor = "meld"
editor = ["nvim", "--cmd", "let g:flatten_wait=1"]

[aliases]
# Graph only up to master
l = ["log", "-r", "(main..@):: | (main..@)-"]
# Diff with meld
diffm = ["diff", "--tool", "meld"]
